config/routes.rb
JSMerchant::Application.routes.draw do
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :price, :description, :image_url
  validates_numericality_of :price

  def price=(input)
    input.delete!("$")
    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, :notice  => "Successfully updated product."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, :notice => "Successfully destroyed product."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def print_price(price)
    number_to_currency price
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodWorks - Products <%= controller.action_name %></title>
    <%= stylesheet_link_tag "styles.css" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <p style="color: green"><%= flash[:notice] %></p>
      <div class="wrapper">
          <div class="header">
            <h1>FoodWorks</h1>
            <p>Your Online Grocery</p>
          </div>

          <div class="sidebar">
            (sidebar)  
          </div>

          <div class="main">
            <%= yield %>
          </div>
       
          <div class="footer">
            FoodWorks Online Grocery<br/>
            A Rails Jumpstart Project
          </div>
      </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :price, "Price (like 2.99)" %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/products/edit.html.erb
<% title "Edit Product" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>

app/views/products/index.html.erb
<% title "All products" %>

<table>
  <tr>
    <th>Image</th>
    <th>Title</th>
    <th>Price</th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag "/images/products/#{product.image_url}" %></td>
      <td><span class="product_title"><%= link_to product.title, product_path(product) %></span><%= product.description %></td>
      <td><%= print_price(product.price) %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Create a New Product", new_product_path %>

app/views/products/new.html.erb
<% title "Create a New Product" %>

<%= render 'form' %>

<p><%= link_to "Back to List", products_path %></p>

app/views/products/show.html.erb
<% title "Product" %>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Image Url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>